### ISSUE TITLE
Unable to link your skill

### ISSUE THREAD

**Issue by skysteve** [Geit/alexa-monzo#17]
Hey,

I keep getting "Unable to link your skill" errors any idea what I'm doing wrong?

In monzo I've set the redirect urls to "https://layla.amazon.co.uk/api/skill/link/M2ZMQNS2VXCBTQ" and confidential set to true

In the alexa skill I've got
- client ID: "oauthclient_00....."
- the 2 urls are correct
- the Client Authentication Scheme is set to "Credentials in request body"

If I open the email from monzo on my phone alexa app opens and there's no confirmation and the "Link account" button still shows. If I open it on my laptop I get the unable to link your skill error.

Any pointers would be much appreciated,
Cheers
Steve

**Comment by Geit** [comment]
The client authentication scheme should be HTTP Basic, I believe. Everything else sounds right.

My Alexa settings page looks like this:
![Alexa Settings](https://geit.uk/uploads/T2qV4q.png)

**Comment by skysteve** [comment]
seems I had alexa signed in to a different amazon account to my browser! thanks for your help :)
