### ISSUE TITLE
Authorising the skill

### ISSUE THREAD

**Issue by nr077961** [Geit/alexa-monzo#26]
I'm having terrible difficulty authorising the Alexa skill.

I just keep getting a message saying that the skill can't be authorised and to try again later.

Any help would be appreciated.

Thanks!

**Comment by rpmhoward** [comment]
Hey, I only got the skill working earlier today. Are you referring to the skill itself or linking the skill to your monzo account?

**Comment by nr077961** [comment]
Linking it to my Monzo account, I've hit a brick wall.

**Comment by rpmhoward** [comment]
I'm guessing you've carried out the steps regarding enabling the account linking in the README?

**Comment by nr077961** [comment]
Yes, many times...

**Comment by nr077961** [comment]
I just get this screen
![img_0181](https://cloud.githubusercontent.com/assets/7492232/21554533/425143c4-ce08-11e6-89c3-8db15357e17e.PNG)

**Comment by rpmhoward** [comment]
Is this after following the link monzo send you in the authentication email? (You'll receive one after following the steps to link your account from the link account button)

**Comment by nr077961** [comment]
Yes, when I get the email from them, I click it and that screen appears.

**Comment by nr077961** [comment]
I think I have the API set up wrong. Can someone tell me how it should be set up please? I can't find anything on the web.

**Comment by rpmhoward** [comment]
Once you have enabled account linking, this is what I have:
Authorization URL: https://auth.getmondo.co.uk/
Client ID: \<Client ID from developers.getmondo.co.uk\>

I did nothing with Domain List or Scope

I copied the two redirect URLs to developers.getmondo.co.uk comma delimited as the clients redirect URLs

Authorisation Grant Type: Auth Code Grant
Access Token URI: https://api.monzo.com/oauth2/token
Client Secret: \<Client Secret from developers.getmondo.co.uk\>
Client Authentication Scheme: HTTP Basic

I should also mention I set the OAuth client as confidential when registering it at developers.getmondo.co.uk

**Comment by nr077961** [comment]
Ok so I was trying to link the account using the Alexa app on my phone. I've just done it through a web browser and it's working great!
