### ISSUE TITLE
The remote endpoint could not be called, or the response it returned was invalid.

### ISSUE THREAD

**Issue by xxgeoffreyxx** [Geit/alexa-monzo#28]
Having trouble testing the skill - when I try a few of the sample utterances, I get the above error. Not sure if it's related, but in the lambda console when I try to run a simple test, I get the following error:

```
{
  "errorMessage": "Cannot find module '/var/task/index'",
  "errorType": "Error",
  "stackTrace": [
    "Module.require (module.js:353:17)",
    "require (internal/module.js:12:17)"
  ]
}
```
Any ideas what I could be doing wrong? 

Edit: I'm guessing it's down to what I've labelled as the handler. I've tried index.handler (as above), Alexa, alexa, alexa-monzo, and monzo.

**Comment by Geit** [comment]
I believe this one is because the zip you uploaded isn't "flat". Lambda expects the directory structure to be flat when the zip is unpacked, or for you to prefix a folder name to your handler if you upload it inside non-flat zip.

This zip is built off the latest master as an example of a flat zip.
http://geit.uk/uploads/alexa-monzo.zip

```
Handler set to index.handler
--> alexa-monzo.zip
----> index.js

Handler set to alexa-monzo/index.handler
--> alexa-monzo.zip
----> alexa-monzo
------> index.js
```

**Comment by xxgeoffreyxx** [comment]
I’m doing this on a Mac, but I did triple check that the ZIP file was flat,
i.e. on exploding you see the contents and not a folder then contents.

I’ll try zipping the folder with Archive Exporer instead of finder and
circle back. Thanks!


On January 11, 2017 at 10:39:33 AM, Rory King (notifications@github.com)
wrote:

I believe this one is because the zip you uploaded isn't "flat". Lambda
expects the directory structure to be flat when the zip is unpacked, or for
you to prefix a folder name to your handler if you upload it inside
non-flat zip.

This zip is built off the latest master as an example of what I mean:
http://geit.uk/uploads/alexa-monzo.zip

Handler set to index.handler
--> alexa-monzo.zip
----> index.js

Handler set to alexa-monzo/index.handler
--> alexa-monzo.zip
----> alexa-monzo
------> index.js

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Geit/alexa-monzo/issues/28#issuecomment-271835775>, or mute
the thread
