### ISSUE TITLE
"sorry - something went wrong"

### ISSUE THREAD

**Issue by sunscreem** [Geit/alexa-monzo#30]
All seems good when I try my skill in the developers console, but when I try it on an actual device I just get "sorry something went wrong".

Any tips of where to start debugging? Or do I just need to be patient and wait for it to update on all my devices? (If that's a thing?)

**Comment by Geit** [comment]
Hi @sunscreem - Did you manage to get this fixed? - for some reason GitHub doesn't notify me for new issues on this repo :(

**Comment by sunscreem** [comment]
Hey - no rush. I was just having a play to see if I could get this work. I've not got any further with it to be honest. Any tips for where to start debugging?

**Comment by Geit** [comment]
If Lamda is working correctly - it should set up logging for you in CloudWatch - any error should hopefully be logged there:

![image](https://user-images.githubusercontent.com/762130/36946468-5dea10fc-1fb5-11e8-8092-f8aec605596d.png)

**Comment by sunscreem** [comment]
Brill. I'll have a dig in when I get a "spare 5 minutes" (in quotes as its pretty much laughable) this week and re-open the issue if I get stuck.

**Comment by danjohnson95** [comment]
Just in case anyone is stuck with this and the logs aren't outputting anything, my mistake was that I was developing for *English U.S* but my device was set to *English U.K*.

You'll need to copy over the relevant skill manifest to the language of your device to be able to use it on that device.
